# Change these first
owner: KazuoID # Your GitHub organization or username, where this repository lives
repo: upptime-v2 # The name of this repository

sites:
  - name: v1 (adrian)
    url: https://www.adrianmh.my.id
  - name: v2 (aal)
    url: https://www.alfeus.my.id
  - name: v3 (ardhana)
    url: https://www.angelarp.my.id
  - name: v4 (angelina)
    url: https://www.angellll.my.id
  - name: v5 (felix)
    url: https://www.christianfelix.my.id
  - name: v6 (davin)
    url: https://www.davin.my.id
  - name: v7 (elia)
    url: https://www.elia3.my.id
  - name: v8 (fidelis)
    url: https://www.fidelisalledeo.my.id
  - name: v9 (filemon)
    url: https://www.filemon.my.id
  - name: v10 (gabriel)
    url: https://www.patricio1.my.id
  - name: v11 (hugo)
    url: https://www.hubertushugo.my.id
  - name: v12 (imanuel)
    url: https://www.imanuel.my.id
  - name: v13 (sandy)
    url: https://www.pntaaa.my.id
  - name: v14 (jasmine)
    url: https://www.jasminedaniela.my.id
  - name: v15 (jojo)
    url: https://www.jojoandros.my.id
  - name: v16 (nathan)
    url: https://www.nathan18.my.id
  - name: v17 (jovian)
    url: https://www.jovianalexa.my.id
  - name: v18 (krismenda)
    url: https://www.krismenda.my.id
  - name: v19 (leon)
    url: https://www.leonjoseph17.my.id
  - name: v20 (lucky)
    url: https://www.luckymarvel1.my.id
  - name: v21 (adit / rizqi)
    url: https://www.ryuxyro.my.id
  - name: v22 (max)
    url: https://www.maxfrederick.my.id
  - name: v23 (michael)
    url: https://www.michaeladrimiwa.my.id
  - name: v24 (not found)
    url: https://
  - name: v25 (dewa)
    url: https://www.putraalikramsadewa.my.id
  - name: v26 (aldo)
    url: https://www.revaldo.my.id
  - name: v27 (reyhan)
    url: https://www.reyhanhrtnt.my.id 
  - name: v28 (rizky)
    url: https://www.rizkydashboard11.my.id
  - name: v29 (tessa)
    url: https://www.tessalonica.my.id
  - name: v30 (vincen)
    url: https://www.vincensius88.my.id
  - name: v31 (gio)
    url: https://www.giovan.my.id
  - name: v32 (widi)
    url: https://www.sjayaaa.my.id
  - name: v33 (wisnu)
    url: https://www.wisputra0202.my.id
  - name: v34 (elkan)
    url: https://www.yohaneselkannathanael.my.id
    
#  - name:
#    url: https://


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-v2
  logoUrl: https://raw.githubusercontent.com/KazuoID/upptime-v2/master/static/img/icon.svg
  name: tekaje Upptime
  introTitle: "**Upptime** is a website monitor for status page, monitoring some student website in **X TKJ 2** class"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/KazuoID/upptime-v2).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
